actionBar:
  # - {sleeping_count}
  # - {candidate_count}
  # - {threshold_count}
  thresholdNotYetReached: '&aEs sind &2{sleeping_count}&a/&2{threshold_count} &abenötigen Spielern im Bett'
  # - {sleeping_count}
  # - {candidate_count}
  # - {threshold_count}
  thresholdReached: '&aDie Nacht wird durchgeschlafen'

chat:
  noCommandPermission: '&7[&5BBTweaks&7] &cDir fehlen die Zugriffsrechte für diesen Befehl!'
  # - {command_label}
  commandUsage: '&7[&5BBTweaks&7] &cBenutzung: /{command_label} <{action_list}>'
  configurationReloaded: '&7[&5BBTweaks&7] &aDie Konfiguration wurde erneut geladen.'
  setRdBreakerNoValidItem: '&7[&5BBTweaks&7] &cDu hältst kein valides Item in der Hand!'
  setRdBreakerMetadata: '&7[&5BBTweaks&7] &aDieses Item ist nun als RD-Breaker gekennzeichnet.'
  getUuidUsage: '&7[&5BBTweaks&7] &cBenutzung: /{command_label} <Name>'
  getUuidUnknownName: '&7[&5BBTweaks&7] &cKonnte zum Namen &4{name} &ckeine UUID finden!'
  getUuidResult: '&7[&5BBTweaks&7] &7Die UUID von &a{name} &7ist &a{uuid}&7!'
  getUuidResultHover: '&aKlicke, um die UUID zu kopieren!'
  backCommandMessage: '&6Du kehrst zur letzten Position zurück.'

unCraft:
  chat:
    inGameOnly: '&8[&6UC&8] &cDieser Befehl ist nur für Spieler verfügbar!'
    missingPermission: '&8[&6UC&8] &cDir fehlt das nötige Recht, um diesen Befehl benutzen zu können!'
    noItemInMainHand: '&8[&6UC&8] &cDu hältst kein Item in deiner Haupthand!'
    unsupportedItem: '&8[&6UC&8] &cDas von dir gehaltene Item wird nicht unterstützt!'
    invalidSelection: '&8[&6UC&8] &cUngültige Auswahl: &4{selection}&c!'
    notEnoughItems: '&8[&6UC&8] &cVom Item &4{result_item} &cwerden mindestens &4{required_amount} Stück &cbenötigt!'
    droppedItems: '&8[&6UC&8] &7Dein Inventar ist &6voll &7- items wurden &6gedroppt&7!'
    resultEntry: '&a{result_amount}x {result_item}'
    resultSeparator: '&7, '
    choicesHeadline: '&8[&6UC&8] &7Bitte entscheide dich für ein Rezept mit &a/{label} <Nummer>&7:'
    choicesEntry: '&7- &a#{choice_number}&7: &a{results}'
    successfulUnCraftUnitOne: '&8[&6UC&8] &7Das Item &a{uncrafted_item} &7wurde &a{uncraft_count}x &7in insgesamt &a{results} &7zurückentwickelt!'
    successfulUnCraftUnitMany: '&8[&6UC&8] &7Das Item &a{uncrafted_item} &7wurde &a{uncraft_count}x &7je &a{uncraft_unit} Stück &7in insgesamt &a{results} &7zurückentwickelt!'

additionalShapedRecipes:
  light-blocks:
    result: LIGHT
    amount: 1
    shape:
      - AAA
      - ABA
      - AAA
    ingredients:
      A:
        type: GLASS_PANE
      B:
        type: TORCH