actionBar:
  # - {sleeping_count}
  # - {candidate_count}
  # - {threshold_count}
  thresholdNotYetReached: '&aEs sind &2{sleeping_count}&a/&2{threshold_count} &abenötigen Spielern im Bett'
  # - {sleeping_count}
  # - {candidate_count}
  # - {threshold_count}
  thresholdReached: '&aDie Nacht wird durchgeschlafen'

chat:
  noCommandPermission: '&7[&5BBTweaks&7] &cDir fehlen die Zugriffsrechte für diesen Befehl!'
  # - {command_label}
  commandUsage: '&7[&5BBTweaks&7] &cBenutzung: /{command_label} <{action_list}>'
  configurationReloaded: '&7[&5BBTweaks&7] &aDie Konfiguration wurde erneut geladen.'
  setRdBreakerNoValidItem: '&7[&5BBTweaks&7] &cDu hältst kein valides Item in der Hand!'
  setRdBreakerMetadata: '&7[&5BBTweaks&7] &aDieses Item ist nun als RD-Breaker gekennzeichnet.'
