actionBar:
  # - {sleeping_count}
  # - {candidate_count}
  # - {threshold_count}
  thresholdNotYetReached: '&aEs sind &2{sleeping_count}&a/&2{threshold_count} &abenötigen Spielern im Bett'
  # - {sleeping_count}
  # - {candidate_count}
  # - {threshold_count}
  thresholdReached: '&aDie Nacht wird durchgeschlafen'

chat:
  noCommandPermission: '&7[&5BBTweaks&7] &cDir fehlen die Zugriffsrechte für diesen Befehl!'
  # - {command_label}
  commandUsage: '&7[&5BBTweaks&7] &cBenutzung: /{command_label} <{action_list}>'
  configurationReloaded: '&7[&5BBTweaks&7] &aDie Konfiguration wurde erneut geladen.'
  setRdBreakerNoValidItem: '&7[&5BBTweaks&7] &cDu hältst kein valides Item in der Hand!'
  setRdBreakerMetadata: '&7[&5BBTweaks&7] &aDieses Item ist nun als RD-Breaker gekennzeichnet.'
  getUuidUsage: '&7[&5BBTweaks&7] &cBenutzung: /{command_label} <Name>'
  getUuidUnknownName: '&7[&5BBTweaks&7] &cKonnte zum Namen &4{name} &ckeine UUID finden!'
  getUuidResult: '&7[&5BBTweaks&7] &7Die UUID von &a{name} &7ist &a{uuid}&7!'
  getUuidResultHover: '&aKlicke, um die UUID zu kopieren!'
  backCommandMessage: '&6Du kehrst zur letzten Position zurück.'

# If some events of a teleportation are to be ignored selectively, they may be described as an entry of this list.
# For example, the elevators of CraftBook would be "com.sk89q.craftbook.mechanics.Elevator#teleportPlayer".
# Each entry down below can be made up of comma-separated and case-insensitive keywords, for abbreviation and generality.
# Thus, "craftbook,elevator" would suffice to match the fully-qualified name mentioned above.
back-in-listener-ignore-list:
  - 'craftbook,elevator'