unCraft:
  typeExclusionRules:
    -
      onUnCraftedItem: true
      tags:
        - ITEMS_HEAD_ARMOR
        - ITEMS_CHEST_ARMOR
        - ITEMS_LEG_ARMOR
        - ITEMS_FOOT_ARMOR
        - ITEMS_PICKAXES
        - ITEMS_AXES
        - ITEMS_SHOVELS
        - ITEMS_HOES
        - ITEMS_SWORDS
        - ITEMS_SPEARS
      materials:
        - FISHING_ROD
        - FLINT_AND_STEEL
        - SHEARS
        - BRUSH
      reason: Rüstungen, Werkzeuge und Waffen werden durch die Wiederverwertungsblöcke (Salvage-Skill) von mcMMO gehandhabt
    -
      onUnCraftedItem: true
      materials:
        - WHEAT_SEEDS
        - MELON_SEEDS
        - PUMPKIN_SEEDS
        - SUGAR
      reason: Dieses Item kann nicht weiter zurückentwickelt werden
    -
      onUnCraftedItem: true
      materialPatterns:
        - '^(.*_)?COPPER_CHEST$'
      reason: Kann durch einen Kupfergolem generiert werden
    -
      onUnCraftedItem: true
      materials:
        - DIORITE
        - GRANITE
      reason: Enthält Quarz und kommt natürlich vor
    -
      onUnCraftedItem: true
      materials:
        - RED_SANDSTONE
        - SANDSTONE
      reason: Würde das Farmen von Sand stark vereinfachen
    -
      onUnCraftedItem: true
      materials:
        - NETHER_WART_BLOCK
      reason: Enthält Netherwarzen und kommt natürlich vor
    -
      onUnCraftedItem: true
      materials:
        - DRIED_GHAST
      reason: Enthält Ghasttränen und kommt natürlich vor
    -
      onUnCraftedItem: true
      materialPatterns:
        - '^.*_SMITHING_TEMPLATE$'
      reason: Rezepte mit Schmiedevorlagen werden ausschließlich zum Vervielfachen benutzt
    -
      onUnCraftedItem: true
      materialPatterns:
        - '^.*_DYE$'
      reason: Farbstoffe haben oft keinen klaren Ursprung und würden unfaire Items erzeugen
    -
      onUnCraftResult: true
      materialPatterns:
        - '^WAXED_.*$'
      reason: Gewachste Items werden niemals ausgegeben.
    -
      onUnCraftedItem: true
      materialIsFlags:
        - isEdible
      reason: Nahrung enthält Items, die gefarmt werden müssten und kommt natürlich vor
    -
      # Because that makes absolutely no sense in reverse - what would the map be filled with?
      onUnCraftResult: true
      materials:
        - FILLED_MAP
      reason: Das Rezept mit einer gefüllten Karte wird ausschließlich zum Vervielfachen benutzt
    -
      onUnCraftResult: true
      materials:
        - VINE
      reason: Dieses Item beinhaltet Ranken und kommt natürlich vor
    -
      onUnCraftResult: true
      materials:
        - MOSS_BLOCK
        - PALE_MOSS_BLOCK
      reason: Dieses Item beinhaltet Moos und kommt natürlich vor
    -
      onUnCraftResult: true
      materialPatterns:
        - '^.*(_BOTTLE|_BUCKET)$'
      reason: Das Rezept dieses Items beinhaltet Behälter wie Flaschen oder Eimer, die beim Craften leer retourniert wurden
    -
      onUnCraftResult: true
      tags:
        - ITEMS_SKULLS
      reason: Enthält Köpfe, die im Allgemeinen ausgenommen wurden
    -
      onUnCraftResult: true
      materialPatterns:
        - '^.*_WOOD$'
      reason: Holz (Stamm mit Rinde an allen Seiten) wird nicht ausgegeben
    -
      onUnCraftedItem: true
      onUnCraftResult: true
      materials:
        - GOLDEN_APPLE
        - ENCHANTED_GOLDEN_APPLE
      reason: Enthält Gold und kommt relativ häufig natürlich vor
    -
      onUnCraftedItem: true
      materials:
        - DARK_PRISMARINE
        - PRISMARINE
        - PRISMARINE_BRICKS
      reason: Enthält Farbstoffe und/oder Prismarinscherben und kommt häufig natürlich vor
  resultSubtractionRules:
    -
      materialPatterns:
        - '^.*_TERRACOTTA$'
        - '^.*_WOOL$'
      subtractedMaterials:
        -
          materialPatterns:
            - '^.*_DYE$'
    -
      materialPatterns:
        - '^WAXED_.*$'
      subtractedMaterials:
        -
          materials:
            - HONEYCOMB
  typeInclusionRules:
  recipeExclusionRules:
    -
      # These are already deconstruction-recipes; inverting them again makes no sense.
      recipes:
        - '9 BONE_MEAL -> 1 BONE_BLOCK'
        - '9 COAL -> 1 COAL_BLOCK'
        - '9 COPPER_INGOT -> 1 COPPER_BLOCK'
        - '9 COPPER_NUGGET -> 1 COPPER_INGOT'
        - '9 DIAMOND -> 1 DIAMOND_BLOCK'
        - '9 DRIED_KELP -> 1 DRIED_KELP_BLOCK'
        - '9 EMERALD -> 1 EMERALD_BLOCK'
        - '9 GOLD_INGOT -> 1 GOLD_BLOCK'
        - '9 GOLD_NUGGET -> 1 GOLD_INGOT'
        - '9 IRON_INGOT -> 1 IRON_BLOCK'
        - '9 IRON_NUGGET -> 1 IRON_INGOT'
        - '9 LAPIS_LAZULI -> 1 LAPIS_BLOCK'
        - '9 NETHERITE_INGOT -> 1 NETHERITE_BLOCK'
        - '9 RAW_COPPER -> 1 RAW_COPPER_BLOCK'
        - '9 RAW_GOLD -> 1 RAW_GOLD_BLOCK'
        - '9 RAW_IRON -> 1 RAW_IRON_BLOCK'
        - '9 REDSTONE -> 1 REDSTONE_BLOCK'
        - '9 RESIN_CLUMP -> 1 RESIN_BLOCK'
        - '9 SLIME_BALL -> 1 SLIME_BLOCK'
        - '9 WHEAT -> 1 HAY_BLOCK'
      reason: Dieses Item kann nicht weiter zurückentwickelt werden
    -
      recipes:
        - '1 STICK -> 2 BAMBOO'
      reason: Würde die Umwandlung von Holz zu Bambus ermöglichen
    -
      recipes:
        - '4 STICK -> 2 OAK_PLANKS'
      reason: Wird von einem Rezept mit schlechterer Umwandlungsrate ersetzt (8 für 1)
    -
      recipes:
        - '4 ACACIA_PLANKS -> 1 OAK_LOG'
        - '4 BIRCH_PLANKS -> 1 OAK_LOG'
        - '4 CHERRY_PLANKS -> 1 OAK_LOG'
        - '4 CRIMSON_PLANKS -> 1 OAK_LOG'
        - '4 DARK_OAK_PLANKS -> 1 OAK_LOG'
        - '4 JUNGLE_PLANKS -> 1 OAK_LOG'
        - '4 MANGROVE_PLANKS -> 1 OAK_LOG'
        - '4 PALE_OAK_PLANKS -> 1 OAK_LOG'
        - '4 SPRUCE_PLANKS -> 1 OAK_LOG'
        - '4 WARPED_PLANKS -> 1 OAK_LOG'
      reason: Wird von Rezepten mit spezifischer Sorte überschrieben (Schwachstelle meines automatischen Filters)
  additionalRecipes:
    -
      recipe: '8 STICK -> 1 OAK_PLANKS'
    -
      recipe: '1 CAKE -> 1 CAKE'
      additionalMessages:
        - '<&e><&o>*The cake is a lie!*'
    - recipe: '4 ACACIA_PLANKS -> 1 ACACIA_LOG'
    - recipe: '4 BIRCH_PLANKS -> 1 BIRCH_LOG'
    - recipe: '4 CHERRY_PLANKS -> 1 CHERRY_LOG'
    - recipe: '4 CRIMSON_PLANKS -> 1 CRIMSON_STEM'
    - recipe: '4 DARK_OAK_PLANKS -> 1 DARK_OAK_LOG'
    - recipe: '4 JUNGLE_PLANKS -> 1 JUNGLE_LOG'
    - recipe: '4 MANGROVE_PLANKS -> 1 MANGROVE_LOG'
    - recipe: '4 PALE_OAK_PLANKS -> 1 PALE_OAK_LOG'
    - recipe: '4 SPRUCE_PLANKS -> 1 SPRUCE_LOG'
    - recipe: '4 WARPED_PLANKS -> 1 WARPED_STEM'
  preferredMaterials:
    -
      tags:
        - ITEMS_PLANKS
      preferredMaterial: OAK_PLANKS
    -
      tags:
        - ITEMS_WOODEN_SLABS
      preferredMaterial: OAK_SLAB
    -
      tags:
        - ITEMS_LOGS
      preferredMaterial: OAK_LOG
    -
      tags:
        - ITEMS_SAND
      preferredMaterial: SAND
    -
      tags:
        - ITEMS_WOOL
      preferredMaterial: WHITE_WOOL
    -
      tags:
        - ITEMS_STONE_CRAFTING_MATERIALS
      preferredMaterial: COBBLESTONE
